# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58636076a67390b5c45b5ef16f166b2e9f0e22cf1da9afba3bf7b09970b86b55f43291f36cfeb2b8cfdf80200ac4ad5452d34929e0d65a0d49fda85d83440e95

test:
  secret_key_base: 685fca6bfa4bb61c7baab7133d438e10fe71c4bdc01f28d4410a92ea9c3d27febde051d4a38b9e2d0e726d13c26d92afe33494334e20c709b9bd1b4a3db77a27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
